spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/nathbitpos
    username: snnsoluciones
    password: "@39NSNm90@1"
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: fe@samyx.digital
    password: facturas@samyx@1018
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

# Configuración NathBit API
nathbit:
  api:
    url: https://api.nathbit.com  # Cambiar en producción
    api-key: nathbit-mailreceptor-2024-secure-key-change-this

# IMAP
imap:
  host: imap.gmail.com
  port: 993

server:
  port: 5002

logging:
  level:
    digital:
      samyx:
        mailreceptor: DEBUG