
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://137.184.208.221:3306/samyx_prod?ssl-mode=REQUIRED
    username: sammy
    password: _NHrX37=%#wV

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect

  ##enviar respuesta
  mail:
    host: smtp.gmail.com
    port: 587
    username: fe@samyx.digital
    password: facturas@samyx@1018
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  jmx:
    default-domain: MensajeReceptorInbox Javier

correo:
  de:
    distribucion: fe@samyx.digital
  no:
    reply: fe@samyx.digital

path:
  upload:
    files:
      api: /home/XmlClientes/

api:
  host: smtp.gmail.com

server:
  servlet:
    session:
      timeout: 720m
      cookie:
        max-age: 720m
logging:
  level:
    digital:
      samyx:
        mailreceptor: DEBUG