spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:fe@samyx.digital}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

nathbit:
  api:
    url: https://api.nathbit.com  # Cambiar en producción
    api-key: ${NATHBIT_API_KEY}

imap:
  host: imap.gmail.com
  port: 993

server:
  port: 5002

logging:
  level:
    digital.samyx.mailreceptor: INFO